# ECSI MULTIGROUP ANALYSIS



## INTRODUCTION

## METHODOLOGY

Covariance-based SEM ( CB-SEM)
is primarily used to confirm (or reject) theories (i.e., a set of systematic
relationships between multiple variables that can be tested empirically).
It does this by determining how well a proposed theoretical
model can estimate the covariance matrix for a sample data set. In
contrast, PLS-SEM (also called PLS path modeling) is primarily used
to develop theories in exploratory research. It does this by focusing
on explaining the variance in the dependent variables when examining
the model.

## ECSI MODEL EQUATIONS

The general form of the structural model of ECSI is:

$$\eta =\beta\eta + \gamma \xi + \nu $$

$$E( \nu | \xi) = 0$$

where $\eta = (\eta_1, \eta_2, \dots, \eta_6)$ is the vector of endogenous latent variables:

- $\eta_1$ : customer expectations; 
- $\eta_2$ : perceived quality of products and services;
- $\eta_3$ : perceived value;
- $\eta_4$ : customer satisfaction (ECSI);
- $\eta_5$ : complaints;
- $\eta_6$ : customer loyalty.


$\xi$ is the exogenous latent variable (image), $\beta$ is the matrix of coeficients of $\eta$, $\gamma$ is the vector of coeficients of $\xi$, and $\nu$ is the vector of errors. 


$\begin{bmatrix}\eta_1\\ \eta_2\\ \eta_3\\ \eta_4\\ \eta_5\\ \eta_6\\ \end{bmatrix} =
\begin{bmatrix} 0&0&0&0&0&0\\ \beta_{21}&0&0&0&0&0 \\ \beta_{31}&\beta_{32}&0&0&0&0 \\ \beta_{41}&\beta_{42}&\beta_{43}&0&0&0 \\ 0&0&0&\beta_{54}&0&0 \\ 0&0&0&\beta_{64}&\beta_{65}&0 \\ \end{bmatrix} 
\begin{bmatrix}\eta_1\\ \eta_2\\ \eta_3\\ \eta_4\\ \eta_5\\ \eta_6\\ \end{bmatrix} +
\begin{bmatrix} \gamma_1\\ 0 \\ 0 \\ \gamma_4\\ 0 \\ \gamma_6\\ \end{bmatrix} \xi + 
\begin{bmatrix} \nu_1\\ \nu_2 \\ \nu_3 \\ \nu_4 \\ \nu_5 \\ \nu_6 \\ \end{bmatrix}$ 

#### Conceptual Model

## ECSI INNER MODEL

![ECSI Inner Model](images/ECSI_graph_3.png "ECSI Inner Model")

## ECSI OUTER MODEL

### DATA DISTRIBUTION

The responses are requested using a 10-point scale, then the distribution of the answers in each of the possible response categories (1, 2, 3, ... , 10) can be calculated and displayed in a table or chart.

<pre>
-----------------
| Questão | Descrição | Valores
|:---:|:----|:----|
| Q2 | Ano a partir do qual o inquirido é cliente do banco | 9999 – NS/NR |
| Q3 | Grau de satisfação global com o banco | 1_10 <br>99: NS/NR | 
| Q4A | Banco de confiança no que diz e no que faz | 1_10 <br>99: NS/NR | 
| Q4B | Banco perfeitamente implantado no mercado | 1_10 <br>99: NS/NR | 
| Q4C | Contribui positivamente para a sociedade | 1_10 <br>99: NS/NR | 
| Q4D | Preocupa-se com os seus clientes | 1_10 <br>99: NS/NR | 
| Q4E | Banco inovador e virado para o futuro | 1_10 <br>99: NS/NR | 
| Q5A | Expectativas que tinha há seis meses atrás ou quando se tornou cliente do banco relativamente à qualidade global do mesmo | 1_10 <br>99: NS/NR |  
| Q5B | Expectativas que tinha há seis meses atrás ou quando se tornou cliente do banco relativamente à capacidade do mesmo oferecer produtos e serviços que satisfizessem as suas necessidades pessoais |1_10 <br>99: NS/NR |  
| Q5C | Expectativas que tinha há seis meses atrás ou quando se tornou cliente do banco relativamente à capacidade do mesmo evitar falhas ou erros |  1_10 <br>99: NS/NR | 
| Q6 | Qualidade apercebida do banco | 1_10 <br>99: NS/NR | 
| Q7A | Qualidade dos produtos e serviços bancários oferecidos | 1_10 <br>99: NS/NR | 
| Q7B | Atendimento e capacidade de aconselhamento | 1_10 <br>99: NS/NR | 
| Q7C | Acessibilidade a produtos e serviços por via das novas tecnologias | 1_10 <br>99: NS/NR | 
| Q7D | Fiabilidade dos produtos e serviços oferecidos | 1_10 <br>99: NS/NR |  
| Q7E | Diversidade de produtos e serviços | 1_10 <br>99: NS/NR | 
| Q7F | Clareza e transparência na informação fornecida |1_10 <br>99: NS/NR | 
| Q7G | Disponibilidade das agências |1_10 <br>99: NS/NR |  
| Q7H | Qualidade das agências | 1_10 <br>99: NS/NR | 
| Q9 | Realização das expectativas percepcionadas | 1_10 <br>99: NS/NR | 
| Q10 | Classificação dos preços e das taxas dos produtos e serviços do banco, dada a qualidade dos mesmos | 1_10 <br>99: NS/NR | 
| Q11 | Classificação da qualidade dos produtos e serviços do banco, dados os preços e as taxas dos mesmos  | 1_10 <br>99: NS/NR | 
| Q12 | Probabilidade de voltar a escolher o banco no caso de adquirir um produto ou serviço bancário | 1_10 <br>99: NS/NR | 
| Q13 | Diferença a partir da qual mudaria de banco face à redução de comissões, juros e outras taxas em outros bancos | 0_100(%) <br>222: FicaSempreBanco <br>999: NS/NR | 
| Q14 | Apresentação de reclamações  | 1: Sim <br>2: Não | 
| Q15  | (Caso Q14=1) Avaliação da forma como foi tratada a reclamação apresentada  | 1_10 <br>99: NS/NR | 
| Q16  | (Caso Q14=2) Expectativa na forma de resolução de uma possível reclamação | 1_10 <br>99: NS/NR | 
| Q17  | Probabilidade de recomendar o banco a outras pessoas | 1_10 <br>99: NS/NR | 
| Q18  | Medida de proximidade do banco do cliente a um banco que considere ideal | 1_10 9<br>9: NS/NR | 
</pre>
Nota: Nas respostas com escala de 1 a 10, os valores de 1 a 5 correspondem a avaliações negativas e os valores de 6 a 10 correspondem a avaliações
positivas.

<pre>
----------------
|Questão | Descrição | Valores |
|:---:|:----|:----|
| B1 | Género do inquirido | 1-Feminino <br> 2-Masculino | 
| B2 | Ano de nascimento do inquirido | (últimos dois dígitos) <br>99:Revelação recusada | 
| B5 | Situação profissional | 1 – Empregado <br>2 – Desempregado <br>3 – Estudante <br>4 – Doméstico <br>5 – Reformado <br>6 – Outra <br>9 – NS/NR | 
| B6 | (Caso B5=1 ou B5=6) Situação perante a actividade profissional | 1 – Patrão <br>2 – Trabalhador por conta própria <br>3 – Trabalhador por conta de outrem <br>4 – Outra <br>9 – NS/NR | 
| B8 | Nível de instrução escolar | 1 – Não sabe ler nem escrever <br>2 – Sabe ler e escrever sem possuir grau de ensino <br>3 – Ensino básico elementar <br>4 – Ensino básico preparatório <br>5 – Ensino secundário unificado <br>6 – Ensino secundário complementar <br>7 – Cursos médios <br>8 – Ensino superior incompleto <br>9 – Ensino superior completo ou mais <br>99 – NS/NR|
------------------
</pre>

In [1]:
import pandas as pd
import numpy as np

In [2]:
mqm = pd.read_csv('../BD_MQM.csv', index_col = "Respondent", 
                  encoding="utf8", skipinitialspace=True, na_values=['9999','99'])
mqm.describe()

Bank           Q2           Q3          Q4A          Q4B  \
count  1758.000000  1406.000000  1756.000000  1748.000000  1707.000000   
mean      4.008532  1992.160028     5.485592     5.674485     5.946514   
std       2.001546    10.122136     1.182721     1.206779     1.056573   
min       1.000000  1950.000000     0.700000     0.700000     0.700000   
25%       2.000000  1987.000000     4.900000     4.900000     5.600000   
50%       4.000000  1995.000000     5.600000     5.600000     6.300000   
75%       6.000000  2000.000000     6.300000     7.000000     7.000000   
max       7.000000  2005.000000     7.000000     7.000000     7.000000   

               Q4C          Q4D          Q4E          Q5A          Q5B  \
count  1601.000000  1733.000000  1688.000000  1692.000000  1634.000000   
mean      5.383573     5.471956     5.585900     5.216489     5.231151   
std       1.293575     1.376258     1.212952     1.162175     1.210245   
min       0.700000     0.700000     0.700000     0.700000     0.700000   
25%       4.900000     4.900000     4.900000     4.200000     4.200000   
50%       5.600000     5.600000     5.600000     5.600000     5.600000   
75%       6.300000     7.000000     6.300000     5.600000     6.300000   
max       7.000000     7.000000     7.000000     7.000000     7.000000   

          ...              Q15          Q16        Q1516          Q17  \
count     ...       180.000000  1423.000000  1603.000000  1715.000000   
mean      ...         4.087222     5.208433     5.082533     5.393469   
std       ...         2.167563     1.381508     1.531168     1.590136   
min       ...         0.700000     0.700000     0.700000     0.700000   
25%       ...         2.800000     4.200000     4.200000     4.900000   
50%       ...         4.200000     5.600000     5.600000     5.600000   
75%       ...         5.775000     6.300000     6.300000     7.000000   
max       ...         7.000000     7.000000     7.000000     7.000000   

               Q18           B1           B2           B5           B6  \
count  1678.000000  1758.000000  1744.000000  1758.000000  1078.000000   
mean      5.076043     1.432309    62.068807     2.129124     2.833024   
std       1.356311     0.610776    15.669890     1.594257     0.624436   
min       0.700000     1.000000    18.000000     1.000000     1.000000   
25%       4.200000     1.000000    51.000000     1.000000     3.000000   
50%       4.900000     1.000000    64.000000     1.000000     3.000000   
75%       5.600000     2.000000    75.000000     3.000000     3.000000   
max       7.000000     9.000000    88.000000     9.000000     9.000000   

                B8  
count  1749.000000  
mean      5.937107  
std       2.172625  
min       2.000000  
25%       4.000000  
50%       6.000000  
75%       8.000000  
max       9.000000  

[8 rows x 36 columns]

In [3]:
image = ['Q4A', 'Q4B', 'Q4C', 'Q4D', 'Q4E']
expectations = ['Q5A', 'Q5B','Q5C']
perceivedQuality = ['Q6', 'Q7A', 'Q7B', 'Q7C', 'Q7D', 'Q7E', 'Q7F', 'Q7G', 'Q7H']
perceivedValue = ['Q10', 'Q11']
satisfaction = ['Q3', 'Q9', 'Q18']
complaints = ['Q1516']
loyalty = ['Q12', 'Q17']
socio = ['Bank', 'B1', 'B5', 'B6', 'B8']

## LOGISTIC REGRESSION

In [4]:
labels = pd.get_dummies(mqm[socio], columns=['Bank', 'B1', 'B5', 'B6', 'B8'])
features = mqm[['Q2', 'Q3', 'Q4A', 'Q4B', 'Q4C', 'Q4D', 'Q4E', 'Q5A', 'Q5B', 'Q5C', 'Q6', 'Q7A', 'Q7B', 
                'Q7C', 'Q7D', 'Q7E', 'Q7F', 'Q7G', 'Q7H', 'Q9', 'Q10', 'Q11', 'Q12', 'Q13', 'Q14', 
                'Q1516', 'Q17', 'Q18', 'B2']]

In [5]:
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import Imputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier


for label in labels:
    print('## ', list(labels[[label]]))
    train_data, test_data, train_labels, test_labels = train_test_split(features, labels[[label]], 
                                                                       random_state=123)
    imp = Imputer()
    imp.fit(train_data)
    train_data = imp.transform(train_data)
    test_data = imp.transform(test_data)
    modelLogit = LogisticRegression()
    modelLogit = LogisticRegression().fit(train_data, train_labels.values.ravel())
    modelRF = RandomForestClassifier()
    modelRF = RandomForestClassifier(n_estimators=10, random_state=0).fit(train_data, train_labels.values.ravel())
    print("Logit Score: %f" % modelLogit.score(test_data, test_labels.values.ravel()))
    print(confusion_matrix(test_labels, modelLogit.predict(test_data)))
    print("Random Forest Score: %f" % modelRF.score(test_data, test_labels.values.ravel()))
    print(confusion_matrix(test_labels, modelRF.predict(test_data)))
    print(" ")

##  ['Bank_1']
Logit Score: 0.847727
[[372   3]
 [ 64   1]]
Random Forest Score: 0.850000
[[374   1]
 [ 65   0]]
 
##  ['Bank_2']
Logit Score: 0.881818
[[388   0]
 [ 52   0]]
Random Forest Score: 0.881818
[[387   1]
 [ 51   1]]
 
##  ['Bank_3']
Logit Score: 0.863636
[[378   7]
 [ 53   2]]
Random Forest Score: 0.875000
[[382   3]
 [ 52   3]]
 
##  ['Bank_4']
Logit Score: 0.854545
[[376   5]
 [ 59   0]]
Random Forest Score: 0.863636
[[379   2]
 [ 58   1]]
 
##  ['Bank_5']
Logit Score: 0.852273
[[375   0]
 [ 65   0]]
Random Forest Score: 0.845455
[[372   3]
 [ 65   0]]
 
##  ['Bank_6']
Logit Score: 0.850000
[[374   0]
 [ 66   0]]
Random Forest Score: 0.847727
[[372   2]
 [ 65   1]]
 
##  ['Bank_7']
Logit Score: 0.825000
[[360   2]
 [ 75   3]]
Random Forest Score: 0.820455
[[360   2]
 [ 77   1]]
 
##  ['B1_1']
Logit Score: 0.563636
[[ 29 142]
 [ 50 219]]
Random Forest Score: 0.495455
[[ 78  93]
 [129 140]]
 
##  ['B1_2']
Logit Score: 0.570455
[[222  47]
 [142  29]]
Random Forest Score: 0.6